### ISSUE TITLE
Teleinfo is officially supported in esphome dev branch now

### ISSUE THREAD

**Issue by 0hax** [schmurtzm/Teleinfo-TIC-with-ESPhome#3]
Hello,

Small message to let you know that teleinformation is officially supported in esphome dev branch now.
https://github.com/esphome/esphome/pull/1108
So you should no more need to create your custom component.

**Comment by schmurtzm** [comment]
That's a really good news ! I will try that soon !

**Comment by schmurtzm** [comment]
Hello, j'ai zieuté un peu le code, ça a l'air top.
SI je peux donner mon avis, quitte à faire un composant officiel je trouve dommage que tu ne remontes pas un maximum d'étiquettes. 
Bon c'est vrai qu'avec HCHC,HCHP et PAPP on a l'essentiel de ce qui nous interesse... Mais bon tant qu'on y est 😄 

Je pense l'exemple devrait fournir toutes les étiquettes dispo en mode historique, ensuite l'utilisateur pioche ce qui l’intéresse dans l'exemple présent dans la doc ;)

Qu'est ce que tu en penses ?

**Comment by schmurtzm** [comment]
Moi j'ai ça par exemple... Et encore je ne remonte pas toutes les étiquettes à dispo.
![image](https://user-images.githubusercontent.com/7110113/99607571-550fb900-2a0c-11eb-90eb-ea7c6284b876.png)

**Comment by 0hax** [comment]
Hello,
C'est pas forcément clair depuis le code mais tu peux récupérer n'importe quel tag selon ce que tu spécifies dans le yaml.
C'est précisé dans la doc ici: https://github.com/esphome/esphome-docs/commit/ff31428e69e7eee3df4a99d49bdd66c21b1b9580
Par exemple, si tu veux l'intensité instantanée IINST en plus de HCHP HCHC et PAPP:
```
    sensor:
      - platform: teleinfo
        tags:
         - name: "HCHC"
           sensor:
            name: "hchc"
            unit_of_measurement: "Wh"
            icon: mdi:flash
         - name: "HCHP"
           sensor:
            name: "hchp"
            unit_of_measurement: "Wh"
            icon: mdi:flash
         - name: "PAPP"
           sensor:
            name: "papp"
            unit_of_measurement: "VA"
            icon: mdi:flash
         - name: "IINST"
           sensor:
            name: "Intensité"
            unit_of_measurement: "A"
            icon: mdi:flash
        update_interval: 60s
        historical_mode: true
```

En éspérant que ce soit plus clair !

**Comment by schmurtzm** [comment]
ah génial ! Merci pour l'exemple ! Je crois que j'ai lu la doc à une heure trop tardive 😅 
Je vais tester ça en ajoutant quelques étiquettes et je te fais un retour d'expérience.

**Comment by djtef** [comment]
Salut @0hax,
J'ai un peu discuté avec @schmurtzm au sujet de la teleinfo via ESPhome sur le [forum hacf ](https://forum.hacf.fr/t/teleinfo-via-wifi/1077/25?u=djtef). Suite à son conseil je te contacte pour que tu voies mon retour d'expérience de mon test de ton nouveau composant teleinfo.
Pour info je me suis permis d'ajouter quelques corrections sur la doc [ici](https://github.com/esphome/esphome-docs/pull/855).
Pour que ça fonctionne, @schmurtzm a vu qu'il fallait désactiver les logs sur l'UART, ce qui nous semble bizarre vu qu'on n'est pas sur la même broche RX.... Moi j'avais quelques soucis de stabilité, ça semble beaucoup mieux en fixant une adresse IP statique. Mais comme me le conseille @schmurtzm je vais ajouter l'info uptime pour vérifier.
La question que je me pose à présent, c'est si je veux me servir de ces infos pour faire du délestage, est-ce que je peux faire envoyer une alerte instantanément à ESPhome même si je laisse le paramètre `update_interval` à 60s par exemple ? Ne peut-on pas rafraichir la donnée à permanence sur l'ESP mais ne la publier sur HA que toutes les 60s ?
En tout cas merci pour vos dev, je trouvais dommage qu'il n'y ait rien pour HA alors que Jeedom et Domoticz étaient bien couverts !

**Comment by lolorc** [comment]
je pense qu'il faudrait vérifier le checksum aussi, j'ai de nombreuses erreurs, ex 
```
Nov 25 15:34:45 esp32_03/debug [D][tic:097]: tic BASE : 01758^G&^Wwg&538328
Nov 25 15:34:33 esp32_03/debug [V][mqtt:372]: Publish(topic='esp32_03/sensor/index/state' payload='17589' retain=1)                                                                                               │
```

aussi index un mot clef qui pose problème à influxdb on dirait.

je vais regarder si je peux implémenter cela, en plus du changement de l'id de BASE je vais le laisser en W/h

edit: done, j'attends un peu d'avoir une erreur pour voir si mon nouveau sensor_ERRORS remonte correctement puis je publierai mes changement

**Comment by lolorc** [comment]
implémenté la : https://github.com/lolorc/Teleinfo-TIC-with-ESPhome/tree/checksum

**Comment by 0hax** [comment]
> Salut @0hax,
> J'ai un peu discuté avec @schmurtzm au sujet de la teleinfo via ESPhome sur le [forum hacf ](https://forum.hacf.fr/t/teleinfo-via-wifi/1077/25?u=djtef). Suite à son conseil je te contacte pour que tu voies mon retour d'expérience de mon test de ton nouveau composant teleinfo.
> Pour info je me suis permis d'ajouter quelques corrections sur la doc [ici](https://github.com/esphome/esphome-docs/pull/855).
> Pour que ça fonctionne, @schmurtzm a vu qu'il fallait désactiver les logs sur l'UART, ce qui nous semble bizarre vu qu'on n'est pas sur la même broche RX.... Moi j'avais quelques soucis de stabilité, ça semble beaucoup mieux en fixant une adresse IP statique. Mais comme me le conseille @schmurtzm je vais ajouter l'info uptime pour vérifier.


Salut @djtef ,
Merci pour ton retour et ta contribution que je vais essayer de revoir bientôt.
Pour le problème d'uart, sur quelle broche as tu relié la téléinfo ?
De mon côté j'utilise l'UART hardware donc je l'ai branché sur la broche RX (celle à côté du VCC) et j'ai donc désactivé l'uart_logger de esphome pour qu'il n y ait pas de conflits entre les 2.
Je ne recommande pas l'utilisation du SW Serial qui est très buggué et peut rendre l'esp instable.

Voici un exemple de ma configuration qui tourne depuis quelques mois sur 2 sonoff basic (compteur production et consomation)
```
esphome:
  name: teleinfo_pompe
  platform: ESP8266
  board: esp8285
  arduino_version: 2.4.2

wifi:
  ssid: ""
  password: ""

logger:
  baud_rate: 0

mqtt:
  broker: mybroker
  log_topic: log

uart:
  id: uart_bus
  rx_pin: GPIO3
  tx_pin: GPIO1
  baud_rate: 1200
  parity: EVEN
  data_bits: 7

sensor:
  - platform: teleinfo
    tags:
     - name: "HCHC"
       sensor:
        name: "hchc"
        unit_of_measurement: "Wh"
        icon: mdi:flash
     - name: "HCHP"
       sensor:
        name: "hchp"
        unit_of_measurement: "Wh"
        icon: mdi:flash
     - name: "PAPP"
       sensor:
        name: "papp"
        unit_of_measurement: "VA"
        icon: mdi:flash
    update_interval: 60s
    historical_mode: true`
```
> La question que je me pose à présent, c'est si je veux me servir de ces infos pour faire du délestage, est-ce que je peux faire envoyer une alerte instantanément à ESPhome même si je laisse le paramètre `update_interval` à 60s par exemple ? Ne peut-on pas rafraichir la donnée à permanence sur l'ESP mais ne la publier sur HA que toutes les 60s ?
> En tout cas merci pour vos dev, je trouvais dommage qu'il n'y ait rien pour HA alors que Jeedom et Domoticz étaient bien couverts !

Tu pourrais rafraichir plus souvent en modifant le code mais j'ai pas trop compris ce que tu veux dire par 'délestage' ?

Je vais essayer de faire un post sur mon site pour expliquer le montage avec un sonoff basic et comment traiter les données côté home assistant et avoir de beaux graphiques sur Grafana.
